name: Publish VS Code Extension

on:
  # Auto-publish whenever you push a version tag like v1.2.3
  push:
    tags:
      - 'v*.*.*'
  # Allow manual runs from the Actions tab
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint, test & build
        run: |
          npm run lint
          npm run compile
          npm test

      - name: Package VSIX
        run: npx vsce package

      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: context-craft-vsix
          path: "*.vsix"

      - name: Publish to VS Code Marketplace
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: npx vsce publish --packagePath $(ls *.vsix) -p "$VSCE_PAT"

      - name: Publish to Open VSX
        env:
          OVSX_PAT: ${{ secrets.OVSX_PAT }}
        run: npx ovsx publish $(ls *.vsix) -p "$OVSX_PAT" 